config/routes.rb
Rails.application.routes.draw do

namespace :acp do
  resources :users, only: [:index, :edit, :update, :destroy]
  resources :memes, only: [:index, :destroy]
  resources :meme_templates, only: [:index, :destroy]
end
  devise_for :users
  root to: "pages#index", as: "index"
  post "/memes/add_comment" => "memes#add_comment", :as => "add_comment_to_memes"

  resources :meme, only: [] do 
    resources :comments, only: [:create]
    get 'like' => "like#like"
    get 'unlike' => "like#unlike"
  end

  #get
  get "tags/:tag" => "pages#index", as: "show_tag"
  get "memes/new" => "memes#new", as: "newmeme"
  get "meme_templates/new" => "meme_templates#new", as: "newtemplate"
  get "memes/list" => "memes#list", as: "list_meme"
  get "meme_templates/list" => "meme_templates#list", as: "list_meme_template"

  get "memes/:id" => "memes#show", as: "meme"
  get "meme_templates/:id" => "meme_templates#show", as: "meme_template"

  #post
  #post "/like/like" => "like#like", as: "like_meme"

  post "/search" => "pages#search", as: "search_tag", as: "search_tag"


  delete "meme_templates/:id" => "meme_templates#delete", as: "delete_meme_template"
  delete "memes/:id" => "memes#delete", as: "delete_meme"
  post "meme_templates" => "meme_templates#create"
  post "memes" => "memes#create"

end

app/models/meme.rb
class Meme < ActiveRecord::Base

    acts_as_commentable
    acts_as_likeable
    acts_as_taggable_on :tags

    attr_accessor :text_up
    attr_accessor :text_down
    attr_accessor :template_id
    attr_accessor :comment
    validates :title, length: { in: 1..50, :message => "Der Titel muss zwischen 1 und 50 Zeichen lang sein" }
    validates :description, length: { maximum: 200, :message => "Die Beschreibung darf nicht länger als 200 Zeichen sein" }
    validates :text_up, length: { in: 1..120, :message => "Der obere Text für das Meme muss zwischen 1 und 120 Zeichen lang sein" }
    validates :text_down, length: { in: 1..120, :message => "Der untere Text für das Meme muss zwischen 1 und 120 Zeichen lang sein" }
    validates :template_id, length: { in: 1..5, :message => "Es muss ein Template ausgewählt werden" }
    validates :tag_list, length: { maximum: 120, :message => "Die Tags dürfen 120 Zeichen nicht überschreiten" }

    belongs_to :user

end

app/controllers/acp/memes_controller.rb
module Acp
    class MemesController < ApplicationController
        def index
            if (current_user.isadmin)
                @memes = Meme.all.page(params[:page]).per(6)
            else
                flash[:error] = "Sie sind kein Administrator."
                redirect_to index_path
            end
        end

        def destroy
            @meme = Meme.all.find(params[:id])
            @meme.destroy
            File.delete('public/uploads/generated_memes/' + @meme.id.to_s + '.jpg')
            flash[:success] = "Meme wurde gelöscht"
            redirect_to acp_memes_path
        end

    end
end

app/controllers/memes_controller.rb
require 'RMagick'
include Magick

class MemesController < ApplicationController

    def new
        @meme = Meme.new
        #if MemeTemplate.all.count == 0
        #    flash[:error] = "Fehler: Keine Templates verfügbar"
        #    redirect_to index_path
        #end
    end

    def create
        @meme = Meme.new(meme_params)
         if @meme.save 
            if (current_user != nil)
                current_user.memes << @meme  
            end
            Imagemagick_Modul.make_meme(meme_params[:text_up], meme_params[:text_down], meme_params[:template_id], @meme.id)
            redirect_to meme_path(@meme.id.to_s)
        else                    
            render action: "new"
        end 
    end

    def list
        if (current_user != nil)
            @memes = current_user.memes.order('created_at DESC').page(params[:page]).per(3)
        else
            redirect_to index_path
        end

    end

    def show
        if Meme.exists?(:id => params[:id])
            @meme = Meme.find(params[:id])
            @comment = Comment.new(commentable:@meme)
            @comments = Comment.all.where(commentable_id: @meme.id.to_s).page(params[:page]).per(6)
        else
            flash[:error] = "Meme mit dieser ID existiert nicht"
            redirect_to index_path
        end

    end

    def delete
        @meme = current_user.memes.find(params[:id])
        @meme.destroy
        File.delete('public/uploads/generated_memes/' + @meme.id.to_s + '.jpg')
        flash[:success] = "Meme wurde gelöscht"
        redirect_to list_meme_path
    end



    private
    def meme_params
        params.require('meme')
        .permit(:title, :description, :text_up, :text_down, :template_id, :isprivate, :comment, :tag_list)
    end
end

app/helpers/memes_helper.rb
module MemesHelper

	def get_social_tags
		raw('<a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?\'http\':\'https\';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+\'://platform.twitter.com/widgets.js\';fjs.parentNode.insertBefore(js,fjs);}}(document, \'script\', \'twitter-wjs\');</script>
			<iframe src="//www.facebook.com/plugins/like.php?href=' + request.original_url + '%2F&amp;width&amp;layout=button_count&amp;action=like&amp;show_faces=true&amp;share=true&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:21px;" allowTransparency="true"></iframe>')
	end

	def list_available_templates
		str = '<select class="image-picker show-html" name="meme[template_id]">'
		MemeTemplate.all.each do |d| 
			if d.isprivate != true
				str << '<option data-img-src="/uploads/meme_template/template_img/' + d.id.to_s + '/thumb_image.jpg" value="' + d.id.to_s + '">  ' + d.id.to_s + '  </option>'.to_s
			else 
				if current_user != nil && d.user_id == current_user.id 
					str << '<option data-img-src="/uploads/meme_template/template_img/' + d.id.to_s + '/thumb_image.jpg" value="' + d.id.to_s + '">  ' + d.id.to_s + '  </option>'.to_s
				end 
			end 
		end
		str << '</select>'
		return raw(str)
	end

	def get_meme_image_link id
		return '/uploads/generated_memes/' + id.to_s + '.jpg'
	end
end

app/views/memes/_comment.html.erb
<fieldset class="well fieldset-comment">
    <legend class="legend-comment">
        <%= get_username_from_id(comment.user_id) %> - <%= comment.created_at %>
    </legend>
        <p style= "word-wrap: break-word;"><%= comment.comment %></p>
</fieldset>

app/views/memes/_meme.html.erb
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= link_to image_tag(get_meme_image_link(meme.id)), meme_path(meme.id.to_s) %>
      <div class="caption">
        <p style= "word-wrap: break-word;"><b><%= meme.title %></b></p>
        <p>Erstellt: <%= meme.created_at %></p>
        <p>Wird gelistet:
          <% if meme.isprivate == false %>
          Ja
          <% else %>
          Nein
          <% end %>
        </p>
          <p>
            <%= link_to delete_meme_path(meme.id.to_s), :class => 'btn btn-danger', :method => :delete  do %>
            <i class="glyphicon glyphicon-trash"></i> Löschen
            <% end %>
          </p>
      </div>
    </div>
 </div>

app/views/memes/list.html.erb
<div class="page-header">
	<h1>Meine Memes</h1>
</div>
<div align="right">
	<%= link_to newmeme_path, :class => "btn btn-primary btn-lg" do %>
	<i class="glyphicon glyphicon-plus-sign"></i> Neues Meme
	<% end %>
</div>
<br />
<% if @memes.all.count == 0 %>
<%= "Du hast keine Memes erstellt" %>
<% end %>
<div class="row">
	<%= render partial: "memes/meme", collection: @memes %>
</div>
<%= paginate @memes %>

app/views/memes/new.html.erb
<% content_for :title do %>Meme erstellen<% end %>
<div class="page-header">
  <h1>Meme erstellen</h1>
</div>

<% if @meme.errors.any? %>
<div id="error_expl" class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Es traten <%= @meme.errors.count %> Fehler beim anlegen des Memes auf:</h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @meme.errors.messages.each do |msg| %>
      <li><%= msg.last.last.html_safe %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<%= form_for @meme, :html => { :class => "form-horizontal meme" } do |f| %>

<div class='col-md-12'>
  <div class='row'>
    <div class='col-md-12'>
      <fieldset>

        <div class="picker">

          <%= list_available_templates %>

        </div>

        <!-- Text input-->
        <div class='form-group'>
          <%= f.label :title, "Titel", :class => 'control-label' %> <i>(<span id="remaining_chars_meme_title">50</span> Zeichen verbleibend)</i>
          <div class="controls">
            <%= f.text_field :title, :onkeyup => 'showCharLen("meme_title", 50)', :maxlength => 50, :class => 'form-control' %>
          </div>
        </div>

        <!-- Textarea -->
        <div class='form-group'>
          <%= f.label :description, "Beschreibung", :class => 'control-label' %> <i>(<span id="remaining_chars_meme_description">200</span> Zeichen verbleibend) (optional)</i>
          <div class="controls">                     
            <%= f.text_area :description, :onkeyup => 'showCharLen("meme_description", 200)', :maxlength => 200, :class => 'form-control' %>
          </div>
        </div>

        <!-- Textarea -->
        <div class='form-group'>
          <%= f.label :text_up, "Text oben", :class => 'control-label' %> <i>(<span id="remaining_chars_meme_text_up">120</span> Zeichen verbleibend)</i>
          <div class="controls">                     
            <%= f.text_area :text_up, :onkeyup => 'showCharLen("meme_text_up", 120)', :maxlength => 120, :class => 'form-control' %>
          </div>
        </div>

        <!-- Textarea -->
        <div class='form-group'>
          <%= f.label :text_down, "Text unten", :class => 'control-label' %>  <i>(<span id="remaining_chars_meme_text_down">120</span> Zeichen verbleibend)</i>
          <div class="controls">                     
           <%= f.text_area :text_down, :onkeyup => 'showCharLen("meme_text_down", 120)', :maxlength => 120, :class => 'form-control' %>
         </div>
       </div>


       <div class='form-group'>
        <%= f.label :tag_list, "Tags", :class => 'control-label' %><i> (Getrennt durch Kommas) (optional)</i>
        <div class="controls">  
          <%= f.text_field :tag_list, :class => 'form-control', :maxlength => 120 %>
        </div>
      </div>

      <!-- checkbox --> 
      <div class='form-group'>
        <%= f.check_box :isprivate %>
        <%= f.label :isprivate, "Meme nicht auflisten", :class => 'control-label' %>
      </div>

      <!-- Button -->
      <div class='form-group'>
        <div class="controls">
          <%= f.submit "meme erstellen", :class => 'btn btn-primary' %>
        </div>
      </div>

    </fieldset>

    
  </div>
</div>
</div>


<% end %>

app/views/memes/show.html.erb
<% content_for :title do %>
<%= @meme.title %>
<% end %>
<div class="page-header">
  <h1>
  <p style= "word-wrap: break-word;"><%= @meme.title %>
    <% if current_user != nil %>
      <% if current_user.likes?(@meme) %>
        <%= link_to meme_unlike_path(@meme), :class => "btn btn-warning btn-sm" do %>
        <i class="glyphicon glyphicon-thumbs-down"></i> Unlike
        <span class="badge"><%= @meme.likers(User).count %></span>
      <% end %>
    <% else %>
      <%= link_to meme_like_path(@meme), :class => "btn btn-primary btn-sm" do  %>
        <i class="glyphicon glyphicon-thumbs-up"></i> Like
        <span class="badge"><%= @meme.likers(User).count %></span>
      <% end %>
    <% end %>
    <% end %>
  </h1>
  </p>
</div>
<p>
  <b>Erstellt von</b>
  <%= get_username_from_id(@meme.user_id) %>
</p>
<p style= "word-wrap: break-word;">
  <b>Beschreibung</b>
  <%= @meme.description %> 
</p>
<p>
  <b>Erstellt am</b>
  <%= @meme.created_at %>
</p>
<p>
  <b>Wird gelistet:</b> 
  <% if @meme.isprivate == false %>
  <%= "Ja" %>
  <% else %>
  <%= "Nein" %>
  <% end %>
</p>
<p>
  <b>Tags:</b>
  <% @meme.tag_list.each do |var| %>
  <%= link_to show_tag_path(var), :class => "btn btn-default btn-xs" do %>
  <% var %>
  <% end %>
  <% end %>
</p>
<p>
  <%= get_social_tags %>
  <div align="center">
    <%= image_tag get_meme_image_link(@meme.id) %>
  </div>
</p>
<hr>
<form>
  <%= render partial: "memes/comment", collection: @comments %>
</form>
<%= paginate @comments %>
<p>
  <%= form_for [@meme, @comment], :html => { :class => "form-horizontal comment" } do |f| %>
  <div class='form-group'>
    <%= f.label :comment, "Kommentar", :class => 'control-label' %> <i>(<span id="remaining_chars_comment_comment">200</span> Zeichen verbleibend)</i>
    <div class="controls">
      <% if current_user == nil %>
      <%= f.text_area :comment, :class => 'form-control', :onkeyup => 'showCharLen("comment_comment", 200)', :maxlength => 200, :disabled => 'disabled'  %>  
      <% else %>
      <%= f.text_area :comment, :class => 'form-control', :onkeyup => 'showCharLen("comment_comment", 200)', :maxlength => 200 %>  
      <% end %>
    </div>
  </div>
  <div class='form-group'>
    <div class="controls">
      <% if current_user == nil %>
      <%= f.submit "Einloggen zum kommentieren", :class => 'btn btn-primary', :disabled => 'disabled' %>
      <% else %>
      <%= f.submit "Kommentar hinzufügen", :class => 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
  <% end %>

</p>