config/routes.rb
Rails.application.routes.draw do

namespace :acp do
  resources :users, only: [:index, :edit, :update, :destroy]
  resources :memes, only: [:index, :destroy]
  resources :meme_templates, only: [:index, :destroy]
end
  devise_for :users
  root to: "pages#index", as: "index"
  post "/memes/add_comment" => "memes#add_comment", :as => "add_comment_to_memes"

  resources :meme, only: [] do 
    resources :comments, only: [:create]
    get 'like' => "like#like"
    get 'unlike' => "like#unlike"
  end

  #get
  get "tags/:tag" => "pages#index", as: "show_tag"
  get "memes/new" => "memes#new", as: "newmeme"
  get "meme_templates/new" => "meme_templates#new", as: "newtemplate"
  get "memes/list" => "memes#list", as: "list_meme"
  get "meme_templates/list" => "meme_templates#list", as: "list_meme_template"

  get "memes/:id" => "memes#show", as: "meme"
  get "meme_templates/:id" => "meme_templates#show", as: "meme_template"

  #post
  #post "/like/like" => "like#like", as: "like_meme"

  post "/search" => "pages#search", as: "search_tag", as: "search_tag"


  delete "meme_templates/:id" => "meme_templates#delete", as: "delete_meme_template"
  delete "memes/:id" => "memes#delete", as: "delete_meme"
  post "meme_templates" => "meme_templates#create"
  post "memes" => "memes#create"

end

app/views/pages/_meme.html.erb
<div class='col-md-12'>
    <div class='row'>
        <div class='col-md-12'>
            <div class="thumbnail">
              <div class="caption">
              <h3><span style= "word-wrap: break-word;"><%= meme.title %></span>
                    <% if current_user != nil %>
                    <% if current_user.likes?(meme) %>
                    <%= link_to meme_unlike_path(meme), :class => "btn btn-warning btn-sm" do %>
                    <i class="glyphicon glyphicon-thumbs-down"></i> Unlike
                    <span class="badge"><%= meme.likers(User).count %></span>
                    <% end %>
                    <% else %>
                    <%= link_to meme_like_path(meme), :class => "btn btn-primary btn-sm" do  %>
                    <i class="glyphicon glyphicon-thumbs-up"></i> Like
                    <span class="badge"><%= meme.likers(User).count %></span>
                    <% end %>
                    <% end %>
                    <% end %>
                </h3>
                <hr>
                <p>von:
                    <%= get_username_from_id(meme.user_id) %> - erstellt: <%= meme.created_at %>
                    <br />
                    Kommentare: <%= Comment.all.where(commentable_id: meme.id.to_s).count %>
                </p>
                <p>
                    <b>Tags:</b>
                    <% meme.tag_list.each do |var| %>
                    <%= link_to show_tag_path(var), :class => "btn btn-default btn-xs" do %>
                    <% var %>
                    <% end %>
                    <% end %>
                    <p>
                        <%= get_social_tags %>
                    </p>
                </p>
            </div>
            <%= link_to image_tag(get_meme_image_link(meme.id)), meme_path(meme.id.to_s) %>
        </div>
    </div>
</div>
</div>

app/views/pages/index.html.erb
<div class="page-header">
  <h1>Startseite</h1>
</div>
<% if @memes.count == 0 %>
<%= "Keine Einträge" %>
<% end %>
<div class="row">
<%= render partial: "pages/meme", collection: @memes %>
</div>
<%= paginate @memes %>

app/views/pages/search.html.erb
<div class="page-header">
  <h1>Suche nach Tag: <%= @search_tag.to_s %></h1>
</div>
<% if @memes.count == 0 %>
<%= "Keine Einträge" %>
<% end %>
<div class="row">
<%= render partial: "pages/meme", collection: @memes %>
</div>
<%= paginate @memes %>