config/routes.rb
Rails.application.routes.draw do

namespace :acp do
  resources :users, only: [:index, :edit, :update, :destroy]
  resources :memes, only: [:index, :destroy]
  resources :meme_templates, only: [:index, :destroy]
end
  devise_for :users
  root to: "pages#index", as: "index"
  post "/memes/add_comment" => "memes#add_comment", :as => "add_comment_to_memes"

  resources :meme, only: [] do 
    resources :comments, only: [:create]
    get 'like' => "like#like"
    get 'unlike' => "like#unlike"
  end

  #get
  get "tags/:tag" => "pages#index", as: "show_tag"
  get "memes/new" => "memes#new", as: "newmeme"
  get "meme_templates/new" => "meme_templates#new", as: "newtemplate"
  get "memes/list" => "memes#list", as: "list_meme"
  get "meme_templates/list" => "meme_templates#list", as: "list_meme_template"

  get "memes/:id" => "memes#show", as: "meme"
  get "meme_templates/:id" => "meme_templates#show", as: "meme_template"

  #post
  #post "/like/like" => "like#like", as: "like_meme"

  post "/search" => "pages#search", as: "search_tag", as: "search_tag"


  delete "meme_templates/:id" => "meme_templates#delete", as: "delete_meme_template"
  delete "memes/:id" => "memes#delete", as: "delete_meme"
  post "meme_templates" => "meme_templates#create"
  post "memes" => "memes#create"

end

app/views/layouts/_navigation.html.erb
<li><%= link_to 'Vorlage anlegen', newtemplate_path() %></li>
<li><%= link_to 'Meme erstellen', newmeme_path() %></li>

app/views/layouts/_search.html.erb
<div class="form-group">
<%= form_tag(search_tag_path, {:class => 'navbar-form navbar-right'}) do %>
    <%= text_field_tag :search, nil, :class => 'form-control', :placeholder => 'einen tag eingeben'  %>
    <%= submit_tag "suchen", :class => 'btn btn-default' %>
<% end %>
</div>

app/views/layouts/_sidebar.html.erb
<h3>Benutzer</h3>
    <% if user_signed_in? %>
  Eingeloggt als <strong><%= current_user.username %></strong>.
  <ul class="nav nav-list">

  <li>
  <%= link_to list_meme_path do %>
    Meine Memes <span class="badge"><%= current_user.memes.all.count %></span>
  <% end %>
  </li>

  <li>
  <%= link_to list_meme_template_path do %>
    Meine Vorlagen <span class="badge"><%= current_user.meme_templates.all.count %></span>
  <% end %>
  </li>

  <li><%= link_to 'Account bearbeiten', edit_user_registration_path %></li>
  <% if current_user.isadmin? %>
  <li><%= link_to 'Adminbereich', acp_users_path %></li>
  <% end %>
  <li><%= link_to "Ausloggen", destroy_user_session_path, :method => :delete %></li>
  </ul>
<% else %>
  <ul class="nav nav-list">
  <li><%= link_to "Registrieren", new_user_registration_path %></li>
  <li><%= link_to "Einloggen", new_user_session_path %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
    <% if content_for?(:title) %>
      <%= 'MemeGenerator - ' + yield(:title) %>
    <% else %>
      MemeGenerator
    <% end %>
    </title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Memegenerator</a>

        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <%= render 'layouts/navigation' %>
          </ul>
          <%= render 'layouts/search' %>
        </div>

      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <%= render 'layouts/sidebar' %>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; MemeGenerator 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
  <script type="text/javascript">

    jQuery("select.image-picker").imagepicker({
      hide_select:  true,
    });

 

  </script>
</html>